# Generated by Django 2.0.5 on 2018-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180516_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='quiz',
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz_passcode',
            field=models.CharField(default='bla', max_length=8, verbose_name='Subject Password'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
