# Generated by Django 2.0.5 on 2018-05-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180516_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=None, to='quiz.Student'),
            preserve_default=False,
        ),
    ]
