# Generated by Django 2.0.5 on 2018-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='quiz.Student'),
        ),
    ]
