# Generated by Django 2.0.5 on 2018-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180517_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(to='quiz.Group'),
        ),
    ]
