# Generated by Django 2.0.5 on 2018-05-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180517_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='subjectstudent',
            name='student',
            field=models.ManyToManyField(to='quiz.Student'),
        ),
        migrations.AddField(
            model_name='subjectstudent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject'),
        ),
    ]
